version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - python -m pip install poetry
      - python -m poetry config virtualenvs.create false
    post_install:
      - python -m poetry install --with docs

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
