version: 3

tasks:
  docs:
    cmd: sphinx-autobuild docs/ docs/_build/ --watch rtorrent_rpc --port 8920

  bump:
    vars:
      VERSION:
        sh: poetry version -s
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'
