version: 3

tasks:
  docs:
    cmd: sphinx-autobuild docs/ docs/_build/ --watch rtorrent_rpc --port 8920

  patch:
    cmds:
      - pyproject-bump micro
      - task: bump

  bump:
    vars:
      VERSION:
        sh: yq '.project.version' pyproject.toml
    cmds:
      - git add pyproject.toml
      - 'git commit -m "bump: {{.VERSION}}"'
      - 'git tag "v{{.VERSION}}" -m "v{{.VERSION}}"'
