name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: trim21/setup-poetry@dist/v2
      - uses: trim21/install-poetry-project@dist/v2

      - name: run tests
        run: coverage run -a -m pytest

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required

  e2e:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
        working-directory: ./tests/fixtures

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: trim21/setup-poetry@dist/v2
      - uses: trim21/install-poetry-project@dist/v2

      - name: run tests
        run: coverage run -a -m pytest e2e

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
