name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", '3.13']
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - run: pip install -e '.[dev]'

      - name: run tests
        run: coverage run -a -m pytest tests

      - uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required

  e2e:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python: ["3.9", "3.10", "3.11", "3.12", '3.13']

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - run: docker compose up -d
        working-directory: ./e2e/fixtures

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip

      - run: pip install -e '.[dev]'

      - run: docker compose ps
        working-directory: ./e2e/fixtures

      - run: docker compose logs rtorrent-unix
        working-directory: ./e2e/fixtures

      - run: docker compose logs rtorrent-tcp
        working-directory: ./e2e/fixtures

      - name: run tests
        run: coverage run -a -m pytest e2e

      - uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required
