name: test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: 'ubuntu-latest'
    strategy:
      fail-fast: false
      matrix:
        python: [ "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - uses: trim21/setup-poetry@dist/v1
      - uses: trim21/install-poetry-project@dist/v1

      - name: run tests
        run: coverage run -a -m pytest

      - uses: codecov/codecov-action@v4
